//
// Created by toohoo on 2/5/2020.
//

#ifndef OBJECT_ORIENTED_PRO_HEADER_H
#define OBJECT_ORIENTED_PRO_HEADER_H
int my_box1();
int my_box2();
int my_line();
int my_box3();
int my_box4();
int my_public_inherit();
int my_protected_inherit();
int my_private_inherit();
int my_line2();
int my_line3();
int my_line4();
int my_line5();
int my_box5();
int my_box6();
int my_box7();
int my_inherit1();
int my_func_override();
int my_box8();
int my_polymorphism();
int my_data_abstraction();
int my_data_encapsulation();
int my_data_abstract();
int my_file_stream1();
int my_exception();
int self_define_exception();
int my_new_delete_operator();
int two_d_array_alloc();
int three_d_array_malloc();
int my_box10();
int my_namespace1();
int my_namespace2();
int my_namespace3();
int my_namespace4();
int my_template1();
int my_template2();
int my_preprocessor1();
int my_condition_compilation1();
int my_preprocessor2();
int my_macro1();
int my_signal1();
int my_signal2();
int my_multithreading();
int my_vector1();
#endif //OBJECT_ORIENTED_PRO_HEADER_H
